// wod config. data only, no logic, so adding or editing workouts never touches main.js.
// gym list is mostly the classic crossfit benchmarks (the girls and a couple of hero wods)
// with the usual metric loads, home list is bodyweight benchmarks plus a few of our own.
// every wod has a matching rx and scaled version so the two buttons stay in sync.

const WODS = {
  gym: [
    {name:"Fran", format:"21-15-9, For Time", type:"Benchmark: The Girls", emoji:"💀",
      rx:"Thrusters (42.5/30 kg) · Pull-ups",
      scaled:"Thrusters (30/20 kg) · Ring rows or banded pull-ups"},
    {name:"Grace", format:"For Time", type:"Benchmark: The Girls", emoji:"⚡",
      rx:"30 Clean and Jerks (61/43 kg)",
      scaled:"30 Clean and Jerks (40/30 kg)"},
    {name:"Isabel", format:"For Time", type:"Benchmark: The Girls", emoji:"🏋️",
      rx:"30 Snatches (61/43 kg)",
      scaled:"30 Power Snatches (35/25 kg)"},
    {name:"Helen", format:"3 Rounds For Time", type:"Benchmark: The Girls", emoji:"🏃",
      rx:"400m Run · 21 KB Swings (24/16 kg) · 12 Pull-ups",
      scaled:"400m Run · 21 KB Swings (16/12 kg) · 12 Ring rows"},
    {name:"Diane", format:"21-15-9, For Time", type:"Benchmark: The Girls", emoji:"🤸",
      rx:"Deadlifts (102.5/70 kg) · Handstand Push-ups",
      scaled:"Deadlifts (70/47.5 kg) · Pike Push-ups"},
    {name:"Elizabeth", format:"21-15-9, For Time", type:"Benchmark: The Girls", emoji:"💪",
      rx:"Squat Cleans (61/43 kg) · Ring Dips",
      scaled:"Squat Cleans (42.5/30 kg) · Bench Dips"},
    {name:"Karen", format:"For Time", type:"Benchmark: The Girls", emoji:"🎯",
      rx:"150 Wall Balls (9/6 kg)",
      scaled:"100 Wall Balls (6/4 kg)"},
    {name:"Jackie", format:"For Time", type:"Benchmark: The Girls", emoji:"🚣",
      rx:"1000m Row · 50 Thrusters (20/15 kg) · 30 Pull-ups",
      scaled:"1000m Row · 50 Thrusters (empty bar) · 30 Ring rows"},
    {name:"Nancy", format:"5 Rounds For Time", type:"Benchmark: The Girls", emoji:"🏃",
      rx:"400m Run · 15 Overhead Squats (42.5/30 kg)",
      scaled:"400m Run · 15 Front Squats (30/20 kg)"},
    {name:"Kelly", format:"5 Rounds For Time", type:"Benchmark: The Girls", emoji:"📦",
      rx:"400m Run · 30 Box Jumps (60/50 cm) · 30 Wall Balls (9/6 kg)",
      scaled:"400m Run · 30 Box Step-ups (50/40 cm) · 30 Wall Balls (6/4 kg)"},
    {name:"DT", format:"5 Rounds For Time", type:"Hero WOD", emoji:"🫡",
      rx:"12 Deadlifts · 9 Hang Power Cleans · 6 Push Jerks (70/47.5 kg)",
      scaled:"12 Deadlifts · 9 Hang Power Cleans · 6 Push Jerks (50/35 kg)"},
    {name:"Murph", format:"For Time", type:"Hero WOD", emoji:"🎖️",
      rx:"1.6k Run · 100 Pull-ups · 200 Push-ups · 300 Air Squats · 1.6k Run (partition as needed, vest 9/6 kg)",
      scaled:"Half Murph: 800m Run · 50 Pull-ups · 100 Push-ups · 150 Air Squats · 800m Run, no vest"},
    {name:"Fight Gone Bad", format:"3 Rounds, 1 min per station", type:"Benchmark", emoji:"🥊",
      rx:"Wall Balls (9/6 kg) · SDHP (35/25 kg) · Box Jumps (50 cm) · Push Press (35/25 kg) · Row (cals) · 1 min rest",
      scaled:"Wall Balls (6/4 kg) · SDHP (25/15 kg) · Box Step-ups · Push Press (25/15 kg) · Row (cals) · 1 min rest"},
  ],
  home: [
    {name:"Cindy", format:"AMRAP 20", type:"Benchmark: The Girls", emoji:"🔥",
      rx:"5 Pull-ups · 10 Push-ups · 15 Air Squats (needs a pull-up bar)",
      scaled:"5 Towel rows on a sturdy table · 10 Knee Push-ups · 15 Air Squats"},
    {name:"Chelsea", format:"EMOM 30", type:"Benchmark: The Girls", emoji:"⏱️",
      rx:"Every minute: 5 Pull-ups · 10 Push-ups · 15 Air Squats (needs a pull-up bar)",
      scaled:"Hold on as long as you can, then finish the rest as one big AMRAP"},
    {name:"Angie", format:"For Time", type:"Benchmark: The Girls", emoji:"💯",
      rx:"100 Pull-ups · 100 Push-ups · 100 Sit-ups · 100 Air Squats (needs a pull-up bar)",
      scaled:"50 Towel rows · 50 Push-ups · 50 Sit-ups · 50 Air Squats"},
    {name:"Annie", format:"50-40-30-20-10, For Time", type:"Benchmark: The Girls", emoji:"🪢",
      rx:"Double-unders · Sit-ups",
      scaled:"Double the reps of single skips (or line hops) · Sit-ups"},
    {name:"Mary", format:"AMRAP 20", type:"Benchmark: The Girls", emoji:"🤸",
      rx:"5 Handstand Push-ups · 10 Pistols · 15 Pull-ups (needs a pull-up bar)",
      scaled:"5 Pike Push-ups · 10 Pistols to a chair · 15 Towel rows"},
    {name:"Barbara", format:"5 Rounds, rest 3 min between", type:"Benchmark: The Girls", emoji:"😤",
      rx:"20 Pull-ups · 30 Push-ups · 40 Sit-ups · 50 Air Squats (needs a pull-up bar)",
      scaled:"10 Towel rows · 20 Push-ups · 30 Sit-ups · 40 Air Squats"},
    {name:"100 Burpees", format:"For Time", type:"Classic", emoji:"🫠",
      rx:"100 Burpees, chest to floor, jump and clap overhead",
      scaled:"50 Burpees, step back and step in is fine"},
    {name:"Death by Burpees", format:"EMOM Ladder", type:"Classic", emoji:"📈",
      rx:"Minute 1: 1 burpee. Minute 2: 2 burpees. Keep adding one until you can't finish inside the minute",
      scaled:"Same ladder, but start at minute 1 with 1 burpee and cap yourself at 10 minutes"},
    {name:"CFHC Living Room", format:"AMRAP 12", type:"CFHC Original", emoji:"🛋️",
      rx:"10 Alternating Lunges · 10 Push-ups · 20 Mountain Climbers",
      scaled:"10 Alternating Lunges · 10 Knee Push-ups · 10 Mountain Climbers"},
    {name:"CFHC Stairway", format:"For Time", type:"CFHC Original", emoji:"🪜",
      rx:"10 Rounds: run up and down your stairs (or 20 high knees) · 10 Air Squats · 5 Burpees",
      scaled:"6 Rounds of the same, walk the stairs, take breaks, just keep moving"},
  ],
};
